config/routes.rb
Rails.application.routes.draw do
  get 'pages/help'
  get 'page/index'
  get 'search/map', to: 'search#map'
  get 'robots/show'
  get 'about', to: 'pages#about'
  get 'project-team', to: 'pages#project_team'
  get 'links', to: 'pages#links'
  get 'contact', to: 'pages#contact'
  get 'suggest', to: 'pages#suggestion'
  get 'sponsors', to: 'pages#sponsors'
  get 'future-outlook', to: 'pages#future_outlook'
  get 'in-the-media', to: 'pages#in_the_media'
  get '/help/transliteration', to: 'pages#transliteration'
  get '/help/browsing-and-searching', to: 'pages#browsing_and_searching'
  get '/help/legend', to: 'pages#legend'
  get 'news', to: 'pages#news'
  get '/help/helpful-pointers', to: 'pages#helpful_pointers'

  devise_for :users

  namespace :admin do
    get 'home/index'

    get 'texts/:census_id', to: 'texts#edit', constraints: {census_id: /\d\.\d+-?\d+/}
    get 'texts/:census_id/edit', to: 'texts#edit', constraints: {census_id: /\d\.\d+-?\d+/}

    resources :versions, :path => 'changes', :only => [:index, :show]
    resources :comments
    resources :news
    resources :volumes
    resources :journals
    resources :places
    resources :roles
    resources :texts, :id => /[^\/]+/ do
      resources :components
      post 'original', on: :member, to: 'texts#update_original'
    end
    resources :standard_identifiers
    resources :people, :path => 'authors'

    root :to => 'home#index'
  end

  # Error routes
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/privacy'

  root :to => "pages#index"
  resources :search, :only => [:index], to: "search#search"
  # get "search", to: "search#search"
  get 'recent-searches', to: "recent_search#index"
  get 'texts/:id', to: 'texts#show'

  resources :texts, :only => [:index, :show]
  resources :volumes, :only => [:index, :show]
  resources :journals, :only => [:index, :show]
  resources :authors, :only => [:index, :show]
  resources :controlled_name, :only => [:index, :show], :id => /.*/, :path => 'people'

  get 'authors/letter(/:first_letter)', to: 'authors#letter'
  get 'journals/letter(/:first_letter)', to: 'journals#letter'
  get 'volumes/letter(/:first_letter)', to: 'volumes#letter'

  get '/authors/(:id)/profile', to: 'authors#profile'
  get '/authors/(:id)/(:genre)/(:medium)', to: 'authors#show_by_type'

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :country, optional: true

  has_many :publication_places, inverse_of: :place, :dependent => :delete_all
  has_many :texts, :through => :publication_places, :class_name => 'Text'
  accepts_nested_attributes_for :publication_places, reject_if: :all_blank, :allow_destroy => true

  has_paper_trail

  default_scope {order(name: :asc)}

=begin
  after_commit {
    puts "Place record '#{self.id}' was updated. Will now touch related Text record(s)"
    self.texts.each(&:touch)
  }
=end

  def country_name
    if country
      country.name
    end
    nil
  end
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :restrict_access

  def restrict_access
    redirect_to "/" unless current_user && current_user.user_type != 'viewer'
  end

  # GET /places
  # GET /places.json
  def index
    @places = Place.all.page(params[:page])
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
    @texts = @place.texts
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to edit_admin_place_path(@place), notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to edit_admin_place_path(@place), notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to admin_places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_for_paper_trail
    current_user.email
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :country_id, :latitude, :longitude, :subdivision)
    end
end

app/views/admin/places/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= simple_form_for [:admin, @place] do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :subdivision %>
        <%= f.association :country %>
        <%= f.input :latitude %>
        <%= f.input :longitude %>
      </div>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>

</div>

app/views/admin/places/edit.html.erb
<h1>Editing Place</h1>
<div class="col-md-7">
<%= render 'form', place: @place %>
</div>
<div class="col-md-5">
  <h2>Appears in...</h2>
  <ul>
    <% if @texts %>
        <% @texts.each do |text| %>
            <li><%= link_to text.title, edit_admin_text_path(text) %></li>
        <% end %>
    <% end %>
  </ul>
  <%= render partial: 'shared/changes', locals: {versions: @place.versions} %>
</div>

app/views/admin/places/index.html.erb
<div class="row">
  <div class="pagination-stuff col-md-10">
    <%= paginate @places %>
  </div>
  <div class="new-thing col-md-2">
    <%= link_to  '<button class="btn btn-defaul btn-success">+ Add a new place</button>'.html_safe, new_admin_place_path %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ul class="list-group">
      <% @places.each do |place| %>
          <li class="list-group-item">
            <%= link_to place.name, edit_admin_place_path(place) %>
            <%= link_to admin_place_path(place), method: :delete, data: {confirm: 'Are you sure?'} do %>
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <% end %>
          </li>
      <% end %>
    </ul>
    <%= paginate @places %>
  </div>
</div>

app/views/admin/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', admin_places_path %>

app/views/admin/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @place.country %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<%= link_to 'Edit', edit_admin_place_path(@place) %> |
<%= link_to 'Back', admin_places_path %>