config/routes.rb
Rails.application.routes.draw do
  get 'pages/help'
  get 'page/index'
  get 'search/map', to: 'search#map'
  get 'robots/show'
  get 'about', to: 'pages#about'
  get 'project-team', to: 'pages#project_team'
  get 'links', to: 'pages#links'
  get 'contact', to: 'pages#contact'
  get 'suggest', to: 'pages#suggestion'
  get 'sponsors', to: 'pages#sponsors'
  get 'future-outlook', to: 'pages#future_outlook'
  get 'in-the-media', to: 'pages#in_the_media'
  get '/help/transliteration', to: 'pages#transliteration'
  get '/help/browsing-and-searching', to: 'pages#browsing_and_searching'
  get '/help/legend', to: 'pages#legend'
  get 'news', to: 'pages#news'
  get '/help/helpful-pointers', to: 'pages#helpful_pointers'

  devise_for :users

  namespace :admin do
    get 'home/index'

    get 'texts/:census_id', to: 'texts#edit', constraints: {census_id: /\d\.\d+-?\d+/}
    get 'texts/:census_id/edit', to: 'texts#edit', constraints: {census_id: /\d\.\d+-?\d+/}

    resources :versions, :path => 'changes', :only => [:index, :show]
    resources :comments
    resources :news
    resources :volumes
    resources :journals
    resources :places
    resources :roles
    resources :texts, :id => /[^\/]+/ do
      resources :components
      post 'original', on: :member, to: 'texts#update_original'
    end
    resources :standard_identifiers
    resources :people, :path => 'authors'

    root :to => 'home#index'
  end

  # Error routes
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/privacy'

  root :to => "pages#index"
  resources :search, :only => [:index], to: "search#search"
  # get "search", to: "search#search"
  get 'recent-searches', to: "recent_search#index"
  get 'texts/:id', to: 'texts#show'

  resources :texts, :only => [:index, :show]
  resources :volumes, :only => [:index, :show]
  resources :journals, :only => [:index, :show]
  resources :authors, :only => [:index, :show]
  resources :controlled_name, :only => [:index, :show], :id => /.*/, :path => 'people'

  get 'authors/letter(/:first_letter)', to: 'authors#letter'
  get 'journals/letter(/:first_letter)', to: 'journals#letter'
  get 'volumes/letter(/:first_letter)', to: 'volumes#letter'

  get '/authors/(:id)/profile', to: 'authors#profile'
  get '/authors/(:id)/(:genre)/(:medium)', to: 'authors#show_by_type'

end

app/models/volume.rb
class Volume < ApplicationRecord
  default_scope { order(sort_title: :asc) }

  has_many :texts
  has_many :volume_citations, inverse_of: :volume, :dependent => :delete_all

  accepts_nested_attributes_for :volume_citations, reject_if: :all_blank, :allow_destroy => true

  has_paper_trail

  after_commit {
    puts "Volume record '#{self.id}' was updated. Will now touch related Text record(s)"
    self.texts.each(&:touch)
  }

  def has_visible_text
    texts.any?{|text| text.is_hidden == false }
  end

end

app/controllers/admin/volumes_controller.rb
class Admin::VolumesController < ApplicationController
  before_action :set_volume, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :restrict_access

  def restrict_access
    redirect_to "/" unless current_user && current_user.user_type != 'viewer'
  end

  # GET /volumes
  # GET /volumes.json
  def index
    @volumes = Volume.all.page(params[:page])
  end

  # GET /volumes/1
  # GET /volumes/1.json
  def show
  end

  # GET /volumes/new
  def new
    @volume = Volume.new
  end

  # GET /volumes/1/edit
  def edit
    @texts = @volume.texts
  end

  # POST /volumes
  # POST /volumes.json
  def create
    @volume = Volume.new(volume_params)
    @volume.sort_title = volume_params[:title].sub(/^The +/, '').sub(/^An +/, '').sub(/^A +/, '').sub(/:/, '')

    respond_to do |format|
      if @volume.save
        format.html {redirect_to edit_admin_volume_path(@volume), notice: 'Volume was successfully created.'}
        format.json {render :show, status: :created, location: @volume}
      else
        format.html {render :new}
        format.json {render json: @volume.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /volumes/1
  # PATCH/PUT /volumes/1.json
  def update
    respond_to do |format|
      @volume.sort_title = volume_params[:title].sub(/^The +/, '').sub(/^An +/, '').sub(/^A +/, '').sub(/:/, '')
      @volume.save

      if @volume.update(volume_params)
        format.html {redirect_to edit_admin_volume_path(@volume), notice: 'Volume was successfully updated.'}
        format.json {render :show, status: :ok, location: @volume}
      else
        format.html {render :edit}
        format.json {render json: @volume.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /volumes/1
  # DELETE /volumes/1.json
  def destroy
    @volume.destroy
    respond_to do |format|
      format.html {redirect_to admin_volumes_url, notice: 'Volume was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def user_for_paper_trail
    current_user.email
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_volume
    @volume = Volume.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def volume_params
    params.require(:volume).permit(
        :title, :sort_title, :author, :location_id, :date, :brief_result_note,
        # @TODO fix the from_language_id_id problem
        volume_citations_attributes: [:id, :role, :last_name, :first_name, :controlled_name, :from_language_id_id, :to_language_id_id, :source_edition,:_destroy],
    )
  end
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  include ControllersHelper

  layout "public"

  # GET /public/journals
  def index
    default_letter = "A"
    @letter = sanitize_letter(params[:letter], default_letter)
    @is_greek_letter = ('Α'..'Ω').include?(@letter)

    @alpha_params_options = {
      bootstrap3: true,
      include_all: false,
      js: false
    }

    @navigation_list = NavigationList.new(Volume, :sort_title, 'A')

    order_field = @is_greek_letter ? Arel.sql('volumes.sort_title COLLATE "el-GR-x-icu"') : :sort_title

    @volumes = Volume.where("volumes.sort_title LIKE :prefix", prefix: "#{@letter}%")
                     .unscope(:order)
                     .order(order_field)

    @volumes = @volumes.select { |vol| vol.has_visible_text }
  end

  # GET /public/volumes/1
  # TODO don't use multiple controller actions across different Models
  def show
    #redirect_to journals_path(@volume)
    @volume = Volume.find(params[:id])
    @referenced_texts = Text.where(:volume_id => @volume.id).where(:is_hidden => false).order(sort_page_span: :asc)

    @editors = @volume.volume_citations.select { |citation| citation.role == 'editor' }
    @translators = @volume.volume_citations.select { |citation| citation.role == 'translator' }

    @other_contributors = @volume.volume_citations.select { |citation| citation.role != 'editor' && citation.role != 'translator' }

  end

  # Go to the first author whose last name starts with
  # first_letter
  def letter
    first_volume = Volume.where.not(title: [nil, '']) # filter out nils and blanks
                         .where("sort_title LIKE ?", "#{params[:first_letter]}%")
                         .order(:sort_title)
                         .first

    redirect_to(volume_path(first_volume))
  end

end

app/helpers/volumes_helper.rb
module VolumesHelper
end

app/views/admin/volumes/_form.html.erb
<%= simple_form_for [:admin, @volume] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, as: :string %>

    <% if @volume.new_record? %>
      <%= f.input :sort_title, as: :string, label: "Title used for sorting (Available to edit after this record has been created)", :disabled => true %>
    <% else %>
      <%= f.input :sort_title, as: :string, label: "Title used for sorting (required)", :disabled => false %>
    <% end %>

    <%= f.input :author, as: :string %>
    <%= f.input :date %>

    <div class="form-inputs">
      <%= f.input :brief_result_note %>
      <span class="input-form__note">Displays in record lists.</span>
    </div>

    <div>
      <h2>Citations</h2>
    </div>
    <div>
      <div id='citations'>
        <%= f.simple_fields_for :volume_citations do |citation| %>
          <%= render 'volume_citation_fields', :f => citation %>
        <% end %>
        <div class='links'>
          <%= link_to_add_association 'add citation', f, :volume_citations %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/volumes/_volume_citation_fields.html.erb
<div class='nested-fields citaiton-fields'>
  <%= link_to_remove_association "x", f, {:class => 'remove-link'} %>
  <%= f.input :last_name, as: :string %>
  <%= f.input :first_name, as: :string %>
  <%= f.input :controlled_name, as: :string %>
  <%= f.label :role %>
  <%= f.select(:role, [['author', 'author'], ['translator', 'translator'],
                       ['editor', 'editor'], ['illustrator', 'illustrator'],
                       ['intro/front matter author', 'intro/front matter author'], ['back matter author', 'back matter author']],
               {}, :onChange => 'showForTranslator(this)') %>
  <div class="translator-only" style="margin-top: 1em;display: <%= f.object.role === 'translator' ? 'block' : 'none' %>">
    <div class="form-group">
      <%= f.label :from %>
      <%= f.select :from_language_id_id, Language.all.collect {|l| [l.name, l.id]}, :include_blank => true %>
    </div>
    <div class="form-group" ?>
      <%= f.label :to %>
      <%= f.select :to_language_id_id, Language.all.collect {|l| [l.name, l.id]}, :include_blank => true %>
    </div>
    <%= f.input :source_edition, as: :string %>
  </div>
</div>

app/views/admin/volumes/edit.html.erb
<h1>Editing Volume</h1>

<div class="col-md-7">
  <%= render 'form', volume: @volume %>
</div>

<div class="col-md-5">
  <h2>Appears in...</h2>
  <% @texts.each do |text| %>
      <li><%= link_to text.title, edit_admin_text_path(text) %></li>
  <% end %>
  <%= render partial: 'shared/changes', locals: {versions: @volume.versions} %>
</div>

app/views/admin/volumes/index.html.erb
<div class="row">
  <div class="pagination-stuff col-md-10">
    <%= paginate @volumes %>
  </div>
  <div class="new-thing col-md-2">
    <%= link_to  '<button class="btn btn-defaul btn-success">+ Add a new volume</button>'.html_safe, new_admin_volume_path %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ul class="list-group">
      <% @volumes.each do |volume| %>
          <li class="list-group-item">
            <%= link_to volume.title, edit_admin_volume_path(volume) %>
            <%= link_to admin_volume_url(volume), method: :delete, data: {confirm: 'Are you sure?'} do %>
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <% end %>
          </li>
      <% end %>
    </ul>
    <%= paginate @volumes %>
  </div>
</div>

app/views/admin/volumes/new.html.erb
<h1>New Volume</h1>

<%= render 'form', volume: @volume %>

<%= link_to 'Back', admin_volumes_path %>

app/views/admin/volumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @volume.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @volume.author %>
</p>

<p>
  <strong>Date:</strong>
  <%= @volume.date %>
</p>

<%= link_to 'Edit', edit_admin_volume_path(@volume) %> |
<%= link_to 'Back', admin_volumes_path %>