config/routes.rb
Rails.application.routes.draw do
  get 'pages/help'
  get 'page/index'
  get 'search/map', to: 'search#map'
  get 'robots/show'
  get 'about', to: 'pages#about'
  get 'project-team', to: 'pages#project_team'
  get 'links', to: 'pages#links'
  get 'contact', to: 'pages#contact'
  get 'suggest', to: 'pages#suggestion'
  get 'sponsors', to: 'pages#sponsors'
  get 'future-outlook', to: 'pages#future_outlook'
  get 'in-the-media', to: 'pages#in_the_media'
  get '/help/transliteration', to: 'pages#transliteration'
  get '/help/browsing-and-searching', to: 'pages#browsing_and_searching'
  get '/help/legend', to: 'pages#legend'
  get 'news', to: 'pages#news'
  get '/help/helpful-pointers', to: 'pages#helpful_pointers'

  devise_for :users

  namespace :admin do
    get 'home/index'

    get 'texts/:census_id', to: 'texts#edit', constraints: {census_id: /\d\.\d+-?\d+/}
    get 'texts/:census_id/edit', to: 'texts#edit', constraints: {census_id: /\d\.\d+-?\d+/}

    resources :versions, :path => 'changes', :only => [:index, :show]
    resources :comments
    resources :news
    resources :volumes
    resources :journals
    resources :places
    resources :roles
    resources :texts, :id => /[^\/]+/ do
      resources :components
      post 'original', on: :member, to: 'texts#update_original'
    end
    resources :standard_identifiers
    resources :people, :path => 'authors'

    root :to => 'home#index'
  end

  # Error routes
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'pages/privacy'

  root :to => "pages#index"
  resources :search, :only => [:index], to: "search#search"
  # get "search", to: "search#search"
  get 'recent-searches', to: "recent_search#index"
  get 'texts/:id', to: 'texts#show'

  resources :texts, :only => [:index, :show]
  resources :volumes, :only => [:index, :show]
  resources :journals, :only => [:index, :show]
  resources :authors, :only => [:index, :show]
  resources :controlled_name, :only => [:index, :show], :id => /.*/, :path => 'people'

  get 'authors/letter(/:first_letter)', to: 'authors#letter'
  get 'journals/letter(/:first_letter)', to: 'journals#letter'
  get 'volumes/letter(/:first_letter)', to: 'volumes#letter'

  get '/authors/(:id)/profile', to: 'authors#profile'
  get '/authors/(:id)/(:genre)/(:medium)', to: 'authors#show_by_type'

end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :place, optional: true
  belongs_to :see_journal, :class_name => "Journal", :foreign_key => "see_journal_id", optional: true

  has_many :texts
  default_scope { order(sort_title: :asc) }

  has_paper_trail

  after_commit {
    puts "Journal record '#{self.id}' was updated. Will now touch related Text record(s)"
    self.texts.each(&:touch)
  }

  def has_visible_text
    texts.any?{|text| text.is_hidden == false }
  end

end

app/controllers/admin/journals_controller.rb
class Admin::JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :restrict_access

  def restrict_access
    redirect_to "/" unless current_user && current_user.user_type != 'viewer'
  end

  # GET /journals
  # GET /journals.json
  def index
    @journals = Journal.all.page(params[:page])
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
    @texts = @journal.texts
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)
    @journal.sort_title = journal_params[:title].sub(/^The +/, '').sub(/^An +/, '').sub(/^A +/, '').sub(/^Το /, '')

    respond_to do |format|
      if @journal.save
        format.html { redirect_to edit_admin_journal_path(@journal), notice: 'Journal was successfully created.' }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      @journal.sort_title = journal_params[:title].sub(/^The +/, '').sub(/^An +/, '').sub(/^A +/, '')
      @journal.save
      if @journal.update(journal_params)
        format.html { redirect_to edit_admin_journal_path(@journal), notice: 'Journal was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to admin_journals_url, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_for_paper_trail
    current_user.email
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_journal
    @journal = Journal.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def journal_params
    params.require(:journal)
        .permit(:title, :sort_title, :place_id, :issn, :indexed_range,
                :sponsoring_organization, :issn_1, :issn_2, :issn_3, :eissn,
                :url, :first_published, :notes, :brief_result_note, :see_journal_id)
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  include ControllersHelper

  layout "public"

  def index
    default_letter = "A"
    @letter = sanitize_letter(params[:letter], default_letter)
    @is_greek_letter = ('Α'..'Ω').include?(@letter)

    @alpha_params_options = {
      bootstrap3: true,
      include_all: false,
      js: false
    }

    @navigation_list = NavigationList.new(Journal, :sort_title, 'A')

    order_field = @is_greek_letter ? Arel.sql('sort_title COLLATE "el-GR-x-icu"') : :sort_title

    @journals = Journal.where("journals.sort_title LIKE :prefix", prefix: "#{@letter}%")
                       .unscope(:order)
                       .order(order_field)

    @journals = @journals.select { |journal| journal.has_visible_text }
  end

  # GET /public/journals/1
  # TODO don't use multiple controller actions across different Models
  def show
    #redirect_to journals_path(@journals)
    @journal = Journal.find(params[:id])
    @referenced_texts = Text.where(:journal_id => @journal.id).where(:is_hidden => false).order(sort_date: :asc, issue_volume: :asc, issue_number: :asc, sort_page_span: :asc, sort_author: :asc)
  end

  # Go to the first author whose last name starts with
  # first_letter
  def letter
    first_journal = Journal.where.not(title: [nil, '']) # filter out nils and blanks
                           .where("sort_title LIKE ?", "#{params[:first_letter]}%")
                           .order(:sort_title)
                           .first

    redirect_to(journal_path(first_journal))
  end

end

app/views/admin/journals/_form.html.erb
<%= simple_form_for [:admin, @journal] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, as: :string %>
  </div>

  <div class="form-inputs">
    <% if @journal.new_record? %>
      <%= f.input :sort_title, as: :string, label: "Title used for sorting (Available to edit after this record has been created)", :disabled => true %>
    <% else %>
      <%= f.input :sort_title, as: :string, label: "Title used for sorting (required)", :disabled => false %>
    <% end %>
  </div>

  <div class="issn-list">
    <div class="form-inputs">
      <%= f.input :issn, as: :string, label: "ISSNs" %>
    </div>

    <div class="form-inputs">
      <%= f.input :issn_1, as: :string, label: '&nbsp;'.html_safe %>
    </div>

    <div class="form-inputs">
      <%= f.input :issn_2, as: :string, label: '&nbsp;'.html_safe %>
    </div>

    <div class="form-inputs">
      <%= f.input :issn_2, as: :string, label: '&nbsp;'.html_safe %>
    </div>
  </div>

  <div class="form-inputs">
    <%= f.input :eissn, as: :string, label: 'EISSN' %>
  </div>

  <div class="form-inputs">
    <%= f.association :place %>
  </div>

  <div class="form-inputs">
    <%= f.input :sponsoring_organization, label: "Sponsoring organization" %>
  </div>

  <div class="form-inputs">
    <%= f.input :indexed_range, label: "Range of volumes/issues indexed" %>
  </div>

  <div class="form-inputs">
    <%= f.input :first_published, label: "Year of first publication" %>
  </div>

  <div class="form-inputs">
    <%= f.input :url, label: "URL" %>
  </div>

  <div class="form-inputs">
    <%= f.input :notes %>
    <span class="input-form__note">Displays in full record view.</span>
  </div>

  <div class="form-inputs">
    <%= f.input :brief_result_note %>
    <span class="input-form__note">Displays in record lists.</span>
  </div>

  <%= f.association :see_journal, collection: Journal.order(:title), :label_method => lambda { |journal| "#{journal.title}" } %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/admin/journals/edit.html.erb
<h1>Editing Journal</h1>

<div class="col-md-7">
<%= render 'form', journal: @journal %>
</div>
<div class="col-md-5">
  <h2>Appears in...</h2>
  <% @texts.each do |text| %>
      <li><%= link_to text.title, edit_admin_text_path(text) %></li>
  <% end %>
  <%= render partial: 'shared/changes', locals: {versions: @journal.versions} %>
</div>

app/views/admin/journals/index.html.erb
<div class="row">
  <div class="pagination-stuff col-md-10">
    <%= paginate @journals %>
  </div>
  <div class="new-thing col-md-2">
    <%= link_to '<button class="btn btn-defaul btn-success">+ Add a new journal</button>'.html_safe, new_admin_journal_path %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ul class="list-group">
      <% @journals.each do |journal| %>
        <li class="list-group-item">
          <%= link_to journal.title, edit_admin_journal_path(journal) %>
          <%= link_to admin_journal_path(journal), method: :delete, data: {confirm: 'Are you sure?'} do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%= paginate @journals %>
  </div>
</div>

app/views/admin/journals/new.html.erb
<h1>New Journal</h1>

<%= render 'form', journal: @journal %>

<%= link_to 'Back', admin_journals_path %>

app/views/admin/journals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @journal.title %>
</p>

<%= link_to 'Edit', edit_admin_journal_path(@journal) %> |
<%= link_to 'Back', admin_journals_path %>